=== LeResKP/xmltool/tests/exercise.dtd
<!ELEMENT Exercise (number, test*)>
<!ATTLIST Exercise idexercise ID #IMPLIED>
<!ELEMENT test (question, (qcm|mqm)+, comments?)>
<!ELEMENT qcm (choice+)>
<!ELEMENT mqm (choice+)>
<!ELEMENT comments (comment+)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT question (#PCDATA)>
<!ELEMENT choice (#PCDATA)>

<!ATTLIST test idtest ID #IMPLIED>
<!ATTLIST qcm idqcm ID #IMPLIED>
<!ATTLIST mqm idmqm ID #IMPLIED>
<!ATTLIST comments idcomments ID #IMPLIED>
<!ATTLIST comment idcomment ID #IMPLIED>
<!ATTLIST question idquestion ID #IMPLIED>
<!ATTLIST choice idchoice ID #IMPLIED>

=== LeResKP/xmltool/tests/exercise.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE Exercise PUBLIC "http://xmltool.lereskp.fr/static/exercise.dtd" "http://xmltool.lereskp.fr/static/exercise.dtd">
<Exercise idexercise="E1">
  <number>1</number>
  <test idtest="T1">
    <question idquestion="Q1">What is your favorite color?</question>
    <mqm idmqm="MQM1">
      <choice idchoice="CHOICE1">blue</choice>
      <choice idchoice="CHOICE2">red</choice>
      <choice idchoice="CHOICE3">black</choice>
    </mqm>
    <mqm idmqm="MQM2">
      <choice idchoice="CHOICE4">magenta</choice>
      <choice idchoice="CHOICE5">orange</choice>
      <choice idchoice="CHOICE6">yellow</choice>
    </mqm>
    <comments>
      <comment></comment>
    </comments>
  </test>
  <test idtest="T2">
    <question idquestion="Q2">What is your favorite color 2?</question>
    <qcm idqcm="QCM1">
      <choice idchoice="CHOICE7">blue</choice>
      <choice idchoice="CHOICE8">red</choice>
      <choice idchoice="CHOICE9">black</choice>
    </qcm>
    <qcm idqcm="QCM2">
      <choice idchoice="CHOICE10">magenta</choice>
      <choice idchoice="CHOICE11">orange</choice>
      <choice idchoice="CHOICE12">yellow</choice>
    </qcm>
    <comments>
      <comment>My comment 1</comment>
    </comments>
  </test>
</Exercise>
